---
title: Курсовая работа
---

= Курсовая работа

[text-right]
--
 Выполнил студент группы КЭ-413
 Ульданов Данил
--

== Глава 1. Анализ требований

Необходимо разработать устройство имитации работы датчика расхода SEN02141B.

Техническое задание:
Устройство должно по изменению сопротивления резистора на плате
расширения изменять частоту генерации сигналов на порту микроконтроллера.

Формула изменения частоты от напряжения на переменном резисторе:

F = Af + Bf * code ,

где Af,Bf - коэффициенты полинома, насчитанные исходя из предположения, что код
1В соответствует 10Гц, код 3В соответствует 55Гц
code – код АЦП ; F - частота

▪ При напряжении менее 0.9 V частота генерации должна быть 0Гц.

▪ АЦП должно работать в режиме DMA

▪ Период измерения напряжения должен быть 50ms

К измеренному напряжению должен быть применен фильтр вида:

tau = int ((1-e^(-dt/(R*C)), RC > 0 sec), (1, RC<= 0 sec))
"FilteredValue" = "OldFiltered" + ("Value" - "OldValue") * tau,

где dt - 100 мс;

Value – текущее нефильтрованное измеренное значение напряжения;

oldValue - предыдущее фильтрованное значение.

▪ Устройство должна использоваться плату Accessories Shield или Analog Test Shield

▪ Для вывода частоты использовать порт TBD

Для начала определим где находиться переменный резистор и его параметры.
Используемая плата расширения это Accessory Shield, Плата расширения для Arduino с популярными периферийними модулями на плате и Xbee разъемом
Даташит для нее был найден на сайте www.chipdip.ru
Stm32F411RE является основным управляющим чипом платы разработки XNucleo. Она имеет широкий
диапазон напряжений питания, поддерживая напряжение питания 3,3 В и 5 В. Благодаря встроенному 12-разрядному конвертеру рекламы
он может обеспечить 2 ^ 12 = 4096. При напряжении питания 3,3 В
разрешение составляет до 4096 мВ / 3300 = 1,24121212121212 мВ. Когда значение AD равно 1, это соответствует
выходному напряжению 1,24121212121212 мВ.
Дополнительный экран обеспечивает встроенный потенциометр с регулировкой 10k с максимальной
регулируемое выходное напряжение 3,3В. Когда плата разработки питается от источника питания 3,3 В,
выходное значение АЦП находится в диапазоне 0 – 4096. Потенциометр находиться на пине ЫЫЫ
омут

При изменении сопротивления резистора меняеться код который выдает АЦП.
Формула перевода кода АЦП в напряжение
U=A*B/C
где А это полученный код от АЦи
В это опорное напряжение которое подаеться на АЦП, так как АЦП питаеться от тоже напряжения что и микроконтрорлер это напряжение 3.3В
С это разрядность АЦП у нас это 12 разрядный АЦП
Таким образом получаем следуюущую формулу
U=A*3.3В/4096
Упростим и получим
U=A*1,24121212121212, мВ
Следовательно код 1В это 1241 а 3В это 3724
F = Af + Bf * code,
Коэффициент Аf это 22,5 Bf это 13
Для того чтобы уменьшить число преобразований которое выполняет микрокотролер перепишем формулу


При коде АЦП 1117 и меньше отключаем генерацию сигнала.

















