---
title: Курсовая работа
---

= Курсовая работа

[text-right]
--
 Выполнил студент группы КЭ-413
 Ульданов Данил
--

== Глава 1. Анализ требований

Необходимо разработать устройство имитации работы датчика расхода SEN02141B.

Техническое задание:
Устройство должно по изменению сопротивления резистора на плате
расширения изменять частоту генерации сигналов на порту микроконтроллера.

Формула изменения частоты от напряжения на переменном резисторе:

F = Af + Bf * code ,

где Af,Bf - коэффициенты полинома, насчитанные исходя из предположения, что код
1В соответствует 10Гц, код 3В соответствует 55Гц
code – код АЦП ; F - частота

▪ При напряжении менее 0.9 V частота генерации должна быть 0Гц.

▪ АЦП должно работать в режиме DMA

▪ Период измерения напряжения должен быть 50ms

К измеренному напряжению должен быть применен фильтр вида:

tau = int ((1-e^(-dt/(R*C)), RC > 0 sec), (1, RC<= 0 sec))
"FilteredValue" = "OldFiltered" + ("Value" - "OldValue") * tau,

где dt - 100 мс;

Value – текущее нефильтрованное измеренное значение напряжения;

oldValue - предыдущее фильтрованное значение.

▪ Устройство должна использоваться плату Accessories Shield или Analog Test Shield

▪ Для вывода частоты использовать порт TBD

=== Формула изменения частоты от напряжения на переменном резисторе

Для начала определим где находиться переменный резистор и его параметры.
Используемая плата расширения это Accessory Shield, Плата расширения для Arduino с популярными периферийними модулями на плате и Xbee разъемом
Даташит для нее был найден на сайте www.chipdip.ru
Stm32F411RE является основным управляющим чипом платы разработки XNucleo. Она имеет широкий
диапазон напряжений питания, поддерживая напряжение питания 3,3 В и 5 В. Благодаря встроенному 12-разрядному конвертеру рекламы
он может обеспечить 2 ^ 12 = 4096. При напряжении питания 3,3 В
разрешение составляет до 4096 мВ / 3300 = 1,24121212121212 мВ. Когда значение AD равно 1, это соответствует
выходному напряжению 1,24121212121212 мВ.
Дополнительный экран обеспечивает встроенный потенциометр с регулировкой 10k с максимальной
регулируемое выходное напряжение 3,3В. Когда плата разработки питается от источника питания 3,3 В,
выходное значение АЦП находится в диапазоне 0 – 4096. Потенциометр находиться на пине ЫЫЫ
омут

При изменении сопротивления резистора меняеться код который выдает АЦП.
Формула перевода кода АЦП в напряжение
U=A*B/C
где А это полученный код от АЦи
В это опорное напряжение которое подаеться на АЦП, так как АЦП питаеться от тоже напряжения что и микроконтрорлер это напряжение 3.3В
С это разрядность АЦП у нас это 12 разрядный АЦП
Таким образом получаем следуюущую формулу
U=A*3.3В/4096
Упростим и получим
U=A*1,24121212121212, мВ
Следовательно код 1В это 1241 а 3В это 3724
F = Af + Bf * code,
Коэффициент Аf это 22,5 Bf это 13
Для того чтобы уменьшить число преобразований которое выполняет микрокотролер перепишем формулу


При коде АЦП 1117 и меньше отключаем генерацию сигнала.

=== АЦП с возможностью прямого доступа к памяти
DMA (Direct Memory Access) - это модуль, который позволяет устройствам ввода-вывода (например, периферийным устройствам) напрямую обмениваться данными с памятью без участия центрального процессора (CPU). DMA используется для ускорения передачи данных между периферийными устройствами и памятью, что позволяет снизить нагрузку на CPU и улучшить производительность системы.

DMA-контроллер представляет собой аппаратный блок, который управляет передачей данных между периферийными устройствами и памятью. Он имеет свою собственную очередь задач, которые выполняются автономно от CPU. Когда периферийное устройство готово к передаче данных, оно посылает запрос на DMA-контроллер, который запускает передачу данных между устройством и памятью.

Для использования DMA необходимо настроить контроллер DMA и настроить периферийное устройство для работы с DMA. Настройка контроллера DMA включает в себя настройку его режима работы, выбор канала DMA, настройку адресов и размеров передаваемых данных. Настройка периферийного устройства для работы с DMA включает в себя выбор канала DMA, настройку режима работы и настройку адресов и размеров передаваемых данных.

В целом, DMA - это мощный инструмент для ускорения передачи данных между периферийными устройствами и памятью. Он позволяет снизить нагрузку на CPU и увеличить производительность системы.

=== Цифровая фильтрация сигнала


tau = int ((1-e^(-dt/(R*C)), RC > 0 sec), (1, RC<= 0 sec))
"FilteredValue" = "OldFiltered" + ("Value" - "OldValue") * tau,

где dt - 100 мс;

Value – текущее нефильтрованное измеренное значение напряжения;

oldValue - предыдущее фильтрованное значение.

Данная формула определяет экспоненциальный фильтр для измерения напряжения. В качестве фильтра используется RC-цепь, где R - это сопротивление, C - емкость, а dt - время дискретизации. На основании этой формулы можно вычислить значение отфильтрованного напряжения (FilteredValue) на основе предыдущего значения (OldFiltered), текущего значения (Value) и параметров фильтра (R и C).
Экспоненциальный фильтр, который был описан по формуле, является простым и эффективным методом сглаживания данных. Он широко используется в различных областях, таких как обработка сигналов, управление двигателями, электроника и другие области.

Также стоит отметить, что параметры R и C влияют на скорость реакции фильтра и на уровень его подавления. Если выбрать большое значение RC, то фильтр будет медленно реагировать на изменения входного сигнала и более глубоко подавлять высокочастотные помехи. Если же выбрать маленькое значение RC, то фильтр будет быстро реагировать на изменения входного сигнала, но меньше подавлять шум.

Таким образом, правильный выбор параметров фильтра RC позволяет достичь необходимого уровня сглаживания с минимальными помехами и задержкой
Данный фильтр называется экспоненциальным фильтром скользящего среднего (Exponential Moving Average, EMA). Он используется для сглаживания временных рядов и устранения шумов.

В формуле "tau" представляет собой постоянную времени фильтра, которая определяется параметрами R и C. Если RC > 0, то постоянная времени равна RC, а если RC <= 0, то постоянная времени равна 1.

"FilteredValue" - это текущее сглаженное значение, которое рассчитывается на основе предыдущего значения "OldFiltered" и текущего значения "Value", умноженного на постоянную времени фильтра.

Формула "FilteredValue" = "OldFiltered" + ("Value" - "OldValue") * tau" показывает, что новое сглаженное значение зависит от предыдущего сглаженного значения и разницы между текущим и предыдущим значениями. Чем больше постоянная времени фильтра, тем медленнее изменяется сглаженное значение и тем больше шумов оно удаляет


=== ОСРВ
Согласно заданию необходимо проводить измерения каждые 50 мс.
Для этих целей можно использовать операционную систему реального времени (ОСРВ).
С помощью ОСРВ можно создать несколько разнородных задач, выполнение которых будет
происходить в заданные периоды времени. +
Итак, составим задачи для ОСРВ:

. Измерение напряжения при помощи АЦП и запись полученных
данных при помощи DMA в регистры памяти микроконтроллера. +
Данная задача осуществляет считывание с резистора значения в виде кода АЦП,
переводит это напряжение в значение частоты для генерации и посчитанное значение
заносит в память микроконтроллера для другой задачи.

. Задача фильтрации измеренного напряжения. +
Каждые 50 мс данная задача берёт измеренное напряжение из памяти
и применяет к ниму фильтр вида
tau = int ((1-e^(-dt/(R*C)), RC > 0 sec), (1, RC<= 0 sec))
"FilteredValue" = "OldFiltered" + ("Value" - "OldValue") * tau,
где dt - 100 мс;
Value – текущее нефильтрованное измеренное значение напряжения;
oldValue - предыдущее фильтрованное значение.
а после записывает в память новое значение напряжения.

. Перевод значения напряжение в значение частоты для генерации сигнала. +
Данная задача должна посчитать по формуле Частота = 0,0225 * Код АЦП - 13
это значение частоты в Герцах необходимо генерировать на порте TBD,
Затем по DMA данные записываются в память микроконтроллера.

. Генерация сигнала заданной частоты. +







